package org.liujk.spring.boot.quartz.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.liujk.spring.boot.quartz.dao.model.JobInfo;
import org.liujk.spring.boot.quartz.dao.model.JobInfoExample;

public interface JobInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_info
     *
     * @mbggenerated
     */
    int countByExample(JobInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_info
     *
     * @mbggenerated
     */
    int deleteByExample(JobInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_info
     *
     * @mbggenerated
     */
    @Delete({
        "delete from job_info",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_info
     *
     * @mbggenerated
     */
    @Insert({
        "insert into job_info (id, job_name, ",
        "group_name, job_desc, ",
        "job_host, job_url, ",
        "job_cron, job_param, ",
        "job_contacts_email, is_load, ",
        "is_vaild, last_run_id, ",
        "last_run_status, created_at, ",
        "created_by, updated_at, ",
        "update_by, is_delete)",
        "values (#{id,jdbcType=BIGINT}, #{jobName,jdbcType=VARCHAR}, ",
        "#{groupName,jdbcType=VARCHAR}, #{jobDesc,jdbcType=VARCHAR}, ",
        "#{jobHost,jdbcType=VARCHAR}, #{jobUrl,jdbcType=VARCHAR}, ",
        "#{jobCron,jdbcType=VARCHAR}, #{jobParam,jdbcType=VARCHAR}, ",
        "#{jobContactsEmail,jdbcType=VARCHAR}, #{isLoad,jdbcType=INTEGER}, ",
        "#{isVaild,jdbcType=INTEGER}, #{lastRunId,jdbcType=INTEGER}, ",
        "#{lastRunStatus,jdbcType=INTEGER}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{createdBy,jdbcType=VARCHAR}, #{updatedAt,jdbcType=TIMESTAMP}, ",
        "#{updateBy,jdbcType=VARCHAR}, #{isDelete,jdbcType=INTEGER})"
    })
    int insert(JobInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_info
     *
     * @mbggenerated
     */
    int insertSelective(JobInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_info
     *
     * @mbggenerated
     */
    List<JobInfo> selectByExample(JobInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_info
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, job_name, group_name, job_desc, job_host, job_url, job_cron, job_param, ",
        "job_contacts_email, is_load, is_vaild, last_run_id, last_run_status, created_at, ",
        "created_by, updated_at, update_by, is_delete",
        "from job_info",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    JobInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") JobInfo record, @Param("example") JobInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") JobInfo record, @Param("example") JobInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(JobInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_info
     *
     * @mbggenerated
     */
    @Update({
        "update job_info",
        "set job_name = #{jobName,jdbcType=VARCHAR},",
          "group_name = #{groupName,jdbcType=VARCHAR},",
          "job_desc = #{jobDesc,jdbcType=VARCHAR},",
          "job_host = #{jobHost,jdbcType=VARCHAR},",
          "job_url = #{jobUrl,jdbcType=VARCHAR},",
          "job_cron = #{jobCron,jdbcType=VARCHAR},",
          "job_param = #{jobParam,jdbcType=VARCHAR},",
          "job_contacts_email = #{jobContactsEmail,jdbcType=VARCHAR},",
          "is_load = #{isLoad,jdbcType=INTEGER},",
          "is_vaild = #{isVaild,jdbcType=INTEGER},",
          "last_run_id = #{lastRunId,jdbcType=INTEGER},",
          "last_run_status = #{lastRunStatus,jdbcType=INTEGER},",
          "created_at = #{createdAt,jdbcType=TIMESTAMP},",
          "created_by = #{createdBy,jdbcType=VARCHAR},",
          "updated_at = #{updatedAt,jdbcType=TIMESTAMP},",
          "update_by = #{updateBy,jdbcType=VARCHAR},",
          "is_delete = #{isDelete,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(JobInfo record);
}