package org.liujk.spring.boot.quartz.dao.model;

import java.util.Date;

public class JobInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.job_name
     *
     * @mbggenerated
     */
    private String jobName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.group_name
     *
     * @mbggenerated
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.job_desc
     *
     * @mbggenerated
     */
    private String jobDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.job_host
     *
     * @mbggenerated
     */
    private String jobHost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.job_url
     *
     * @mbggenerated
     */
    private String jobUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.job_cron
     *
     * @mbggenerated
     */
    private String jobCron;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.job_param
     *
     * @mbggenerated
     */
    private String jobParam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.job_contacts_email
     *
     * @mbggenerated
     */
    private String jobContactsEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.is_load
     *
     * @mbggenerated
     */
    private Integer isLoad;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.is_vaild
     *
     * @mbggenerated
     */
    private Integer isVaild;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.last_run_id
     *
     * @mbggenerated
     */
    private Integer lastRunId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.last_run_status
     *
     * @mbggenerated
     */
    private Integer lastRunStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.created_by
     *
     * @mbggenerated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.update_by
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.is_delete
     *
     * @mbggenerated
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_info
     *
     * @mbggenerated
     */
    public JobInfo(Long id, String jobName, String groupName, String jobDesc, String jobHost, String jobUrl, String jobCron, String jobParam, String jobContactsEmail, Integer isLoad, Integer isVaild, Integer lastRunId, Integer lastRunStatus, Date createdAt, String createdBy, Date updatedAt, String updateBy, Integer isDelete) {
        this.id = id;
        this.jobName = jobName;
        this.groupName = groupName;
        this.jobDesc = jobDesc;
        this.jobHost = jobHost;
        this.jobUrl = jobUrl;
        this.jobCron = jobCron;
        this.jobParam = jobParam;
        this.jobContactsEmail = jobContactsEmail;
        this.isLoad = isLoad;
        this.isVaild = isVaild;
        this.lastRunId = lastRunId;
        this.lastRunStatus = lastRunStatus;
        this.createdAt = createdAt;
        this.createdBy = createdBy;
        this.updatedAt = updatedAt;
        this.updateBy = updateBy;
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.id
     *
     * @return the value of job_info.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.job_name
     *
     * @return the value of job_info.job_name
     *
     * @mbggenerated
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.group_name
     *
     * @return the value of job_info.group_name
     *
     * @mbggenerated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.job_desc
     *
     * @return the value of job_info.job_desc
     *
     * @mbggenerated
     */
    public String getJobDesc() {
        return jobDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.job_host
     *
     * @return the value of job_info.job_host
     *
     * @mbggenerated
     */
    public String getJobHost() {
        return jobHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.job_url
     *
     * @return the value of job_info.job_url
     *
     * @mbggenerated
     */
    public String getJobUrl() {
        return jobUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.job_cron
     *
     * @return the value of job_info.job_cron
     *
     * @mbggenerated
     */
    public String getJobCron() {
        return jobCron;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.job_param
     *
     * @return the value of job_info.job_param
     *
     * @mbggenerated
     */
    public String getJobParam() {
        return jobParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.job_contacts_email
     *
     * @return the value of job_info.job_contacts_email
     *
     * @mbggenerated
     */
    public String getJobContactsEmail() {
        return jobContactsEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.is_load
     *
     * @return the value of job_info.is_load
     *
     * @mbggenerated
     */
    public Integer getIsLoad() {
        return isLoad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.is_vaild
     *
     * @return the value of job_info.is_vaild
     *
     * @mbggenerated
     */
    public Integer getIsVaild() {
        return isVaild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.last_run_id
     *
     * @return the value of job_info.last_run_id
     *
     * @mbggenerated
     */
    public Integer getLastRunId() {
        return lastRunId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.last_run_status
     *
     * @return the value of job_info.last_run_status
     *
     * @mbggenerated
     */
    public Integer getLastRunStatus() {
        return lastRunStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.created_at
     *
     * @return the value of job_info.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.created_by
     *
     * @return the value of job_info.created_by
     *
     * @mbggenerated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.updated_at
     *
     * @return the value of job_info.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.update_by
     *
     * @return the value of job_info.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.is_delete
     *
     * @return the value of job_info.is_delete
     *
     * @mbggenerated
     */
    public Integer getIsDelete() {
        return isDelete;
    }
}