package org.liujk.spring.boot.quartz.dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class JobInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table job_info
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table job_info
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table job_info
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_info
     *
     * @mbggenerated
     */
    public JobInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_info
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_info
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_info
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_info
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_info
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_info
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_info
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_info
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_info
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_info
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table job_info
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andJobNameIsNull() {
            addCriterion("job_name is null");
            return (Criteria) this;
        }

        public Criteria andJobNameIsNotNull() {
            addCriterion("job_name is not null");
            return (Criteria) this;
        }

        public Criteria andJobNameEqualTo(String value) {
            addCriterion("job_name =", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameNotEqualTo(String value) {
            addCriterion("job_name <>", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameGreaterThan(String value) {
            addCriterion("job_name >", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameGreaterThanOrEqualTo(String value) {
            addCriterion("job_name >=", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameLessThan(String value) {
            addCriterion("job_name <", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameLessThanOrEqualTo(String value) {
            addCriterion("job_name <=", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameLike(String value) {
            addCriterion("job_name like", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameNotLike(String value) {
            addCriterion("job_name not like", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameIn(List<String> values) {
            addCriterion("job_name in", values, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameNotIn(List<String> values) {
            addCriterion("job_name not in", values, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameBetween(String value1, String value2) {
            addCriterion("job_name between", value1, value2, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameNotBetween(String value1, String value2) {
            addCriterion("job_name not between", value1, value2, "jobName");
            return (Criteria) this;
        }

        public Criteria andGroupNameIsNull() {
            addCriterion("group_name is null");
            return (Criteria) this;
        }

        public Criteria andGroupNameIsNotNull() {
            addCriterion("group_name is not null");
            return (Criteria) this;
        }

        public Criteria andGroupNameEqualTo(String value) {
            addCriterion("group_name =", value, "groupName");
            return (Criteria) this;
        }

        public Criteria andGroupNameNotEqualTo(String value) {
            addCriterion("group_name <>", value, "groupName");
            return (Criteria) this;
        }

        public Criteria andGroupNameGreaterThan(String value) {
            addCriterion("group_name >", value, "groupName");
            return (Criteria) this;
        }

        public Criteria andGroupNameGreaterThanOrEqualTo(String value) {
            addCriterion("group_name >=", value, "groupName");
            return (Criteria) this;
        }

        public Criteria andGroupNameLessThan(String value) {
            addCriterion("group_name <", value, "groupName");
            return (Criteria) this;
        }

        public Criteria andGroupNameLessThanOrEqualTo(String value) {
            addCriterion("group_name <=", value, "groupName");
            return (Criteria) this;
        }

        public Criteria andGroupNameLike(String value) {
            addCriterion("group_name like", value, "groupName");
            return (Criteria) this;
        }

        public Criteria andGroupNameNotLike(String value) {
            addCriterion("group_name not like", value, "groupName");
            return (Criteria) this;
        }

        public Criteria andGroupNameIn(List<String> values) {
            addCriterion("group_name in", values, "groupName");
            return (Criteria) this;
        }

        public Criteria andGroupNameNotIn(List<String> values) {
            addCriterion("group_name not in", values, "groupName");
            return (Criteria) this;
        }

        public Criteria andGroupNameBetween(String value1, String value2) {
            addCriterion("group_name between", value1, value2, "groupName");
            return (Criteria) this;
        }

        public Criteria andGroupNameNotBetween(String value1, String value2) {
            addCriterion("group_name not between", value1, value2, "groupName");
            return (Criteria) this;
        }

        public Criteria andJobDescIsNull() {
            addCriterion("job_desc is null");
            return (Criteria) this;
        }

        public Criteria andJobDescIsNotNull() {
            addCriterion("job_desc is not null");
            return (Criteria) this;
        }

        public Criteria andJobDescEqualTo(String value) {
            addCriterion("job_desc =", value, "jobDesc");
            return (Criteria) this;
        }

        public Criteria andJobDescNotEqualTo(String value) {
            addCriterion("job_desc <>", value, "jobDesc");
            return (Criteria) this;
        }

        public Criteria andJobDescGreaterThan(String value) {
            addCriterion("job_desc >", value, "jobDesc");
            return (Criteria) this;
        }

        public Criteria andJobDescGreaterThanOrEqualTo(String value) {
            addCriterion("job_desc >=", value, "jobDesc");
            return (Criteria) this;
        }

        public Criteria andJobDescLessThan(String value) {
            addCriterion("job_desc <", value, "jobDesc");
            return (Criteria) this;
        }

        public Criteria andJobDescLessThanOrEqualTo(String value) {
            addCriterion("job_desc <=", value, "jobDesc");
            return (Criteria) this;
        }

        public Criteria andJobDescLike(String value) {
            addCriterion("job_desc like", value, "jobDesc");
            return (Criteria) this;
        }

        public Criteria andJobDescNotLike(String value) {
            addCriterion("job_desc not like", value, "jobDesc");
            return (Criteria) this;
        }

        public Criteria andJobDescIn(List<String> values) {
            addCriterion("job_desc in", values, "jobDesc");
            return (Criteria) this;
        }

        public Criteria andJobDescNotIn(List<String> values) {
            addCriterion("job_desc not in", values, "jobDesc");
            return (Criteria) this;
        }

        public Criteria andJobDescBetween(String value1, String value2) {
            addCriterion("job_desc between", value1, value2, "jobDesc");
            return (Criteria) this;
        }

        public Criteria andJobDescNotBetween(String value1, String value2) {
            addCriterion("job_desc not between", value1, value2, "jobDesc");
            return (Criteria) this;
        }

        public Criteria andJobHostIsNull() {
            addCriterion("job_host is null");
            return (Criteria) this;
        }

        public Criteria andJobHostIsNotNull() {
            addCriterion("job_host is not null");
            return (Criteria) this;
        }

        public Criteria andJobHostEqualTo(String value) {
            addCriterion("job_host =", value, "jobHost");
            return (Criteria) this;
        }

        public Criteria andJobHostNotEqualTo(String value) {
            addCriterion("job_host <>", value, "jobHost");
            return (Criteria) this;
        }

        public Criteria andJobHostGreaterThan(String value) {
            addCriterion("job_host >", value, "jobHost");
            return (Criteria) this;
        }

        public Criteria andJobHostGreaterThanOrEqualTo(String value) {
            addCriterion("job_host >=", value, "jobHost");
            return (Criteria) this;
        }

        public Criteria andJobHostLessThan(String value) {
            addCriterion("job_host <", value, "jobHost");
            return (Criteria) this;
        }

        public Criteria andJobHostLessThanOrEqualTo(String value) {
            addCriterion("job_host <=", value, "jobHost");
            return (Criteria) this;
        }

        public Criteria andJobHostLike(String value) {
            addCriterion("job_host like", value, "jobHost");
            return (Criteria) this;
        }

        public Criteria andJobHostNotLike(String value) {
            addCriterion("job_host not like", value, "jobHost");
            return (Criteria) this;
        }

        public Criteria andJobHostIn(List<String> values) {
            addCriterion("job_host in", values, "jobHost");
            return (Criteria) this;
        }

        public Criteria andJobHostNotIn(List<String> values) {
            addCriterion("job_host not in", values, "jobHost");
            return (Criteria) this;
        }

        public Criteria andJobHostBetween(String value1, String value2) {
            addCriterion("job_host between", value1, value2, "jobHost");
            return (Criteria) this;
        }

        public Criteria andJobHostNotBetween(String value1, String value2) {
            addCriterion("job_host not between", value1, value2, "jobHost");
            return (Criteria) this;
        }

        public Criteria andJobUrlIsNull() {
            addCriterion("job_url is null");
            return (Criteria) this;
        }

        public Criteria andJobUrlIsNotNull() {
            addCriterion("job_url is not null");
            return (Criteria) this;
        }

        public Criteria andJobUrlEqualTo(String value) {
            addCriterion("job_url =", value, "jobUrl");
            return (Criteria) this;
        }

        public Criteria andJobUrlNotEqualTo(String value) {
            addCriterion("job_url <>", value, "jobUrl");
            return (Criteria) this;
        }

        public Criteria andJobUrlGreaterThan(String value) {
            addCriterion("job_url >", value, "jobUrl");
            return (Criteria) this;
        }

        public Criteria andJobUrlGreaterThanOrEqualTo(String value) {
            addCriterion("job_url >=", value, "jobUrl");
            return (Criteria) this;
        }

        public Criteria andJobUrlLessThan(String value) {
            addCriterion("job_url <", value, "jobUrl");
            return (Criteria) this;
        }

        public Criteria andJobUrlLessThanOrEqualTo(String value) {
            addCriterion("job_url <=", value, "jobUrl");
            return (Criteria) this;
        }

        public Criteria andJobUrlLike(String value) {
            addCriterion("job_url like", value, "jobUrl");
            return (Criteria) this;
        }

        public Criteria andJobUrlNotLike(String value) {
            addCriterion("job_url not like", value, "jobUrl");
            return (Criteria) this;
        }

        public Criteria andJobUrlIn(List<String> values) {
            addCriterion("job_url in", values, "jobUrl");
            return (Criteria) this;
        }

        public Criteria andJobUrlNotIn(List<String> values) {
            addCriterion("job_url not in", values, "jobUrl");
            return (Criteria) this;
        }

        public Criteria andJobUrlBetween(String value1, String value2) {
            addCriterion("job_url between", value1, value2, "jobUrl");
            return (Criteria) this;
        }

        public Criteria andJobUrlNotBetween(String value1, String value2) {
            addCriterion("job_url not between", value1, value2, "jobUrl");
            return (Criteria) this;
        }

        public Criteria andJobCronIsNull() {
            addCriterion("job_cron is null");
            return (Criteria) this;
        }

        public Criteria andJobCronIsNotNull() {
            addCriterion("job_cron is not null");
            return (Criteria) this;
        }

        public Criteria andJobCronEqualTo(String value) {
            addCriterion("job_cron =", value, "jobCron");
            return (Criteria) this;
        }

        public Criteria andJobCronNotEqualTo(String value) {
            addCriterion("job_cron <>", value, "jobCron");
            return (Criteria) this;
        }

        public Criteria andJobCronGreaterThan(String value) {
            addCriterion("job_cron >", value, "jobCron");
            return (Criteria) this;
        }

        public Criteria andJobCronGreaterThanOrEqualTo(String value) {
            addCriterion("job_cron >=", value, "jobCron");
            return (Criteria) this;
        }

        public Criteria andJobCronLessThan(String value) {
            addCriterion("job_cron <", value, "jobCron");
            return (Criteria) this;
        }

        public Criteria andJobCronLessThanOrEqualTo(String value) {
            addCriterion("job_cron <=", value, "jobCron");
            return (Criteria) this;
        }

        public Criteria andJobCronLike(String value) {
            addCriterion("job_cron like", value, "jobCron");
            return (Criteria) this;
        }

        public Criteria andJobCronNotLike(String value) {
            addCriterion("job_cron not like", value, "jobCron");
            return (Criteria) this;
        }

        public Criteria andJobCronIn(List<String> values) {
            addCriterion("job_cron in", values, "jobCron");
            return (Criteria) this;
        }

        public Criteria andJobCronNotIn(List<String> values) {
            addCriterion("job_cron not in", values, "jobCron");
            return (Criteria) this;
        }

        public Criteria andJobCronBetween(String value1, String value2) {
            addCriterion("job_cron between", value1, value2, "jobCron");
            return (Criteria) this;
        }

        public Criteria andJobCronNotBetween(String value1, String value2) {
            addCriterion("job_cron not between", value1, value2, "jobCron");
            return (Criteria) this;
        }

        public Criteria andJobParamIsNull() {
            addCriterion("job_param is null");
            return (Criteria) this;
        }

        public Criteria andJobParamIsNotNull() {
            addCriterion("job_param is not null");
            return (Criteria) this;
        }

        public Criteria andJobParamEqualTo(String value) {
            addCriterion("job_param =", value, "jobParam");
            return (Criteria) this;
        }

        public Criteria andJobParamNotEqualTo(String value) {
            addCriterion("job_param <>", value, "jobParam");
            return (Criteria) this;
        }

        public Criteria andJobParamGreaterThan(String value) {
            addCriterion("job_param >", value, "jobParam");
            return (Criteria) this;
        }

        public Criteria andJobParamGreaterThanOrEqualTo(String value) {
            addCriterion("job_param >=", value, "jobParam");
            return (Criteria) this;
        }

        public Criteria andJobParamLessThan(String value) {
            addCriterion("job_param <", value, "jobParam");
            return (Criteria) this;
        }

        public Criteria andJobParamLessThanOrEqualTo(String value) {
            addCriterion("job_param <=", value, "jobParam");
            return (Criteria) this;
        }

        public Criteria andJobParamLike(String value) {
            addCriterion("job_param like", value, "jobParam");
            return (Criteria) this;
        }

        public Criteria andJobParamNotLike(String value) {
            addCriterion("job_param not like", value, "jobParam");
            return (Criteria) this;
        }

        public Criteria andJobParamIn(List<String> values) {
            addCriterion("job_param in", values, "jobParam");
            return (Criteria) this;
        }

        public Criteria andJobParamNotIn(List<String> values) {
            addCriterion("job_param not in", values, "jobParam");
            return (Criteria) this;
        }

        public Criteria andJobParamBetween(String value1, String value2) {
            addCriterion("job_param between", value1, value2, "jobParam");
            return (Criteria) this;
        }

        public Criteria andJobParamNotBetween(String value1, String value2) {
            addCriterion("job_param not between", value1, value2, "jobParam");
            return (Criteria) this;
        }

        public Criteria andJobContactsEmailIsNull() {
            addCriterion("job_contacts_email is null");
            return (Criteria) this;
        }

        public Criteria andJobContactsEmailIsNotNull() {
            addCriterion("job_contacts_email is not null");
            return (Criteria) this;
        }

        public Criteria andJobContactsEmailEqualTo(String value) {
            addCriterion("job_contacts_email =", value, "jobContactsEmail");
            return (Criteria) this;
        }

        public Criteria andJobContactsEmailNotEqualTo(String value) {
            addCriterion("job_contacts_email <>", value, "jobContactsEmail");
            return (Criteria) this;
        }

        public Criteria andJobContactsEmailGreaterThan(String value) {
            addCriterion("job_contacts_email >", value, "jobContactsEmail");
            return (Criteria) this;
        }

        public Criteria andJobContactsEmailGreaterThanOrEqualTo(String value) {
            addCriterion("job_contacts_email >=", value, "jobContactsEmail");
            return (Criteria) this;
        }

        public Criteria andJobContactsEmailLessThan(String value) {
            addCriterion("job_contacts_email <", value, "jobContactsEmail");
            return (Criteria) this;
        }

        public Criteria andJobContactsEmailLessThanOrEqualTo(String value) {
            addCriterion("job_contacts_email <=", value, "jobContactsEmail");
            return (Criteria) this;
        }

        public Criteria andJobContactsEmailLike(String value) {
            addCriterion("job_contacts_email like", value, "jobContactsEmail");
            return (Criteria) this;
        }

        public Criteria andJobContactsEmailNotLike(String value) {
            addCriterion("job_contacts_email not like", value, "jobContactsEmail");
            return (Criteria) this;
        }

        public Criteria andJobContactsEmailIn(List<String> values) {
            addCriterion("job_contacts_email in", values, "jobContactsEmail");
            return (Criteria) this;
        }

        public Criteria andJobContactsEmailNotIn(List<String> values) {
            addCriterion("job_contacts_email not in", values, "jobContactsEmail");
            return (Criteria) this;
        }

        public Criteria andJobContactsEmailBetween(String value1, String value2) {
            addCriterion("job_contacts_email between", value1, value2, "jobContactsEmail");
            return (Criteria) this;
        }

        public Criteria andJobContactsEmailNotBetween(String value1, String value2) {
            addCriterion("job_contacts_email not between", value1, value2, "jobContactsEmail");
            return (Criteria) this;
        }

        public Criteria andIsLoadIsNull() {
            addCriterion("is_load is null");
            return (Criteria) this;
        }

        public Criteria andIsLoadIsNotNull() {
            addCriterion("is_load is not null");
            return (Criteria) this;
        }

        public Criteria andIsLoadEqualTo(Integer value) {
            addCriterion("is_load =", value, "isLoad");
            return (Criteria) this;
        }

        public Criteria andIsLoadNotEqualTo(Integer value) {
            addCriterion("is_load <>", value, "isLoad");
            return (Criteria) this;
        }

        public Criteria andIsLoadGreaterThan(Integer value) {
            addCriterion("is_load >", value, "isLoad");
            return (Criteria) this;
        }

        public Criteria andIsLoadGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_load >=", value, "isLoad");
            return (Criteria) this;
        }

        public Criteria andIsLoadLessThan(Integer value) {
            addCriterion("is_load <", value, "isLoad");
            return (Criteria) this;
        }

        public Criteria andIsLoadLessThanOrEqualTo(Integer value) {
            addCriterion("is_load <=", value, "isLoad");
            return (Criteria) this;
        }

        public Criteria andIsLoadIn(List<Integer> values) {
            addCriterion("is_load in", values, "isLoad");
            return (Criteria) this;
        }

        public Criteria andIsLoadNotIn(List<Integer> values) {
            addCriterion("is_load not in", values, "isLoad");
            return (Criteria) this;
        }

        public Criteria andIsLoadBetween(Integer value1, Integer value2) {
            addCriterion("is_load between", value1, value2, "isLoad");
            return (Criteria) this;
        }

        public Criteria andIsLoadNotBetween(Integer value1, Integer value2) {
            addCriterion("is_load not between", value1, value2, "isLoad");
            return (Criteria) this;
        }

        public Criteria andIsVaildIsNull() {
            addCriterion("is_vaild is null");
            return (Criteria) this;
        }

        public Criteria andIsVaildIsNotNull() {
            addCriterion("is_vaild is not null");
            return (Criteria) this;
        }

        public Criteria andIsVaildEqualTo(Integer value) {
            addCriterion("is_vaild =", value, "isVaild");
            return (Criteria) this;
        }

        public Criteria andIsVaildNotEqualTo(Integer value) {
            addCriterion("is_vaild <>", value, "isVaild");
            return (Criteria) this;
        }

        public Criteria andIsVaildGreaterThan(Integer value) {
            addCriterion("is_vaild >", value, "isVaild");
            return (Criteria) this;
        }

        public Criteria andIsVaildGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_vaild >=", value, "isVaild");
            return (Criteria) this;
        }

        public Criteria andIsVaildLessThan(Integer value) {
            addCriterion("is_vaild <", value, "isVaild");
            return (Criteria) this;
        }

        public Criteria andIsVaildLessThanOrEqualTo(Integer value) {
            addCriterion("is_vaild <=", value, "isVaild");
            return (Criteria) this;
        }

        public Criteria andIsVaildIn(List<Integer> values) {
            addCriterion("is_vaild in", values, "isVaild");
            return (Criteria) this;
        }

        public Criteria andIsVaildNotIn(List<Integer> values) {
            addCriterion("is_vaild not in", values, "isVaild");
            return (Criteria) this;
        }

        public Criteria andIsVaildBetween(Integer value1, Integer value2) {
            addCriterion("is_vaild between", value1, value2, "isVaild");
            return (Criteria) this;
        }

        public Criteria andIsVaildNotBetween(Integer value1, Integer value2) {
            addCriterion("is_vaild not between", value1, value2, "isVaild");
            return (Criteria) this;
        }

        public Criteria andLastRunIdIsNull() {
            addCriterion("last_run_id is null");
            return (Criteria) this;
        }

        public Criteria andLastRunIdIsNotNull() {
            addCriterion("last_run_id is not null");
            return (Criteria) this;
        }

        public Criteria andLastRunIdEqualTo(Integer value) {
            addCriterion("last_run_id =", value, "lastRunId");
            return (Criteria) this;
        }

        public Criteria andLastRunIdNotEqualTo(Integer value) {
            addCriterion("last_run_id <>", value, "lastRunId");
            return (Criteria) this;
        }

        public Criteria andLastRunIdGreaterThan(Integer value) {
            addCriterion("last_run_id >", value, "lastRunId");
            return (Criteria) this;
        }

        public Criteria andLastRunIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("last_run_id >=", value, "lastRunId");
            return (Criteria) this;
        }

        public Criteria andLastRunIdLessThan(Integer value) {
            addCriterion("last_run_id <", value, "lastRunId");
            return (Criteria) this;
        }

        public Criteria andLastRunIdLessThanOrEqualTo(Integer value) {
            addCriterion("last_run_id <=", value, "lastRunId");
            return (Criteria) this;
        }

        public Criteria andLastRunIdIn(List<Integer> values) {
            addCriterion("last_run_id in", values, "lastRunId");
            return (Criteria) this;
        }

        public Criteria andLastRunIdNotIn(List<Integer> values) {
            addCriterion("last_run_id not in", values, "lastRunId");
            return (Criteria) this;
        }

        public Criteria andLastRunIdBetween(Integer value1, Integer value2) {
            addCriterion("last_run_id between", value1, value2, "lastRunId");
            return (Criteria) this;
        }

        public Criteria andLastRunIdNotBetween(Integer value1, Integer value2) {
            addCriterion("last_run_id not between", value1, value2, "lastRunId");
            return (Criteria) this;
        }

        public Criteria andLastRunStatusIsNull() {
            addCriterion("last_run_status is null");
            return (Criteria) this;
        }

        public Criteria andLastRunStatusIsNotNull() {
            addCriterion("last_run_status is not null");
            return (Criteria) this;
        }

        public Criteria andLastRunStatusEqualTo(Integer value) {
            addCriterion("last_run_status =", value, "lastRunStatus");
            return (Criteria) this;
        }

        public Criteria andLastRunStatusNotEqualTo(Integer value) {
            addCriterion("last_run_status <>", value, "lastRunStatus");
            return (Criteria) this;
        }

        public Criteria andLastRunStatusGreaterThan(Integer value) {
            addCriterion("last_run_status >", value, "lastRunStatus");
            return (Criteria) this;
        }

        public Criteria andLastRunStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("last_run_status >=", value, "lastRunStatus");
            return (Criteria) this;
        }

        public Criteria andLastRunStatusLessThan(Integer value) {
            addCriterion("last_run_status <", value, "lastRunStatus");
            return (Criteria) this;
        }

        public Criteria andLastRunStatusLessThanOrEqualTo(Integer value) {
            addCriterion("last_run_status <=", value, "lastRunStatus");
            return (Criteria) this;
        }

        public Criteria andLastRunStatusIn(List<Integer> values) {
            addCriterion("last_run_status in", values, "lastRunStatus");
            return (Criteria) this;
        }

        public Criteria andLastRunStatusNotIn(List<Integer> values) {
            addCriterion("last_run_status not in", values, "lastRunStatus");
            return (Criteria) this;
        }

        public Criteria andLastRunStatusBetween(Integer value1, Integer value2) {
            addCriterion("last_run_status between", value1, value2, "lastRunStatus");
            return (Criteria) this;
        }

        public Criteria andLastRunStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("last_run_status not between", value1, value2, "lastRunStatus");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(Date value) {
            addCriterion("created_at =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(Date value) {
            addCriterion("created_at <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(Date value) {
            addCriterion("created_at >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("created_at >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(Date value) {
            addCriterion("created_at <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
            addCriterion("created_at <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<Date> values) {
            addCriterion("created_at in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<Date> values) {
            addCriterion("created_at not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(Date value1, Date value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("created_by is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("created_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(String value) {
            addCriterion("created_by =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(String value) {
            addCriterion("created_by <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(String value) {
            addCriterion("created_by >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(String value) {
            addCriterion("created_by >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(String value) {
            addCriterion("created_by <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(String value) {
            addCriterion("created_by <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLike(String value) {
            addCriterion("created_by like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotLike(String value) {
            addCriterion("created_by not like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<String> values) {
            addCriterion("created_by in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<String> values) {
            addCriterion("created_by not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(String value1, String value2) {
            addCriterion("created_by between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(String value1, String value2) {
            addCriterion("created_by not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNull() {
            addCriterion("updated_at is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNotNull() {
            addCriterion("updated_at is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtEqualTo(Date value) {
            addCriterion("updated_at =", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotEqualTo(Date value) {
            addCriterion("updated_at <>", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThan(Date value) {
            addCriterion("updated_at >", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("updated_at >=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThan(Date value) {
            addCriterion("updated_at <", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
            addCriterion("updated_at <=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIn(List<Date> values) {
            addCriterion("updated_at in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotIn(List<Date> values) {
            addCriterion("updated_at not in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtBetween(Date value1, Date value2) {
            addCriterion("updated_at between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
            addCriterion("updated_at not between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNull() {
            addCriterion("update_by is null");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNotNull() {
            addCriterion("update_by is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateByEqualTo(String value) {
            addCriterion("update_by =", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotEqualTo(String value) {
            addCriterion("update_by <>", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThan(String value) {
            addCriterion("update_by >", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThanOrEqualTo(String value) {
            addCriterion("update_by >=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThan(String value) {
            addCriterion("update_by <", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThanOrEqualTo(String value) {
            addCriterion("update_by <=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLike(String value) {
            addCriterion("update_by like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotLike(String value) {
            addCriterion("update_by not like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByIn(List<String> values) {
            addCriterion("update_by in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotIn(List<String> values) {
            addCriterion("update_by not in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByBetween(String value1, String value2) {
            addCriterion("update_by between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotBetween(String value1, String value2) {
            addCriterion("update_by not between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNull() {
            addCriterion("is_delete is null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNotNull() {
            addCriterion("is_delete is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteEqualTo(Integer value) {
            addCriterion("is_delete =", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotEqualTo(Integer value) {
            addCriterion("is_delete <>", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThan(Integer value) {
            addCriterion("is_delete >", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_delete >=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThan(Integer value) {
            addCriterion("is_delete <", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThanOrEqualTo(Integer value) {
            addCriterion("is_delete <=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIn(List<Integer> values) {
            addCriterion("is_delete in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotIn(List<Integer> values) {
            addCriterion("is_delete not in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteBetween(Integer value1, Integer value2) {
            addCriterion("is_delete between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotBetween(Integer value1, Integer value2) {
            addCriterion("is_delete not between", value1, value2, "isDelete");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table job_info
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table job_info
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}