package org.liujk.spring.boot.quartz.dao.model;

import java.util.Date;

public class JobRunLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_run_log.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_run_log.job_id
     *
     * @mbggenerated
     */
    private Long jobId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_run_log.job_name
     *
     * @mbggenerated
     */
    private String jobName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_run_log.group_name
     *
     * @mbggenerated
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_run_log.job_param
     *
     * @mbggenerated
     */
    private String jobParam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_run_log.start_time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_run_log.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_run_log.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_run_log.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_run_log.invoke_url
     *
     * @mbggenerated
     */
    private String invokeUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_run_log.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_run_log.created_by
     *
     * @mbggenerated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_run_log.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_run_log.updated_by
     *
     * @mbggenerated
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_run_log.is_delete
     *
     * @mbggenerated
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_run_log
     *
     * @mbggenerated
     */
    public JobRunLog(Long id, Long jobId, String jobName, String groupName, String jobParam, Date startTime, Date endTime, Integer status, String remark, String invokeUrl, Date createdAt, String createdBy, Date updatedAt, String updatedBy, Integer isDelete) {
        this.id = id;
        this.jobId = jobId;
        this.jobName = jobName;
        this.groupName = groupName;
        this.jobParam = jobParam;
        this.startTime = startTime;
        this.endTime = endTime;
        this.status = status;
        this.remark = remark;
        this.invokeUrl = invokeUrl;
        this.createdAt = createdAt;
        this.createdBy = createdBy;
        this.updatedAt = updatedAt;
        this.updatedBy = updatedBy;
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_run_log.id
     *
     * @return the value of job_run_log.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_run_log.job_id
     *
     * @return the value of job_run_log.job_id
     *
     * @mbggenerated
     */
    public Long getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_run_log.job_name
     *
     * @return the value of job_run_log.job_name
     *
     * @mbggenerated
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_run_log.group_name
     *
     * @return the value of job_run_log.group_name
     *
     * @mbggenerated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_run_log.job_param
     *
     * @return the value of job_run_log.job_param
     *
     * @mbggenerated
     */
    public String getJobParam() {
        return jobParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_run_log.start_time
     *
     * @return the value of job_run_log.start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_run_log.end_time
     *
     * @return the value of job_run_log.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_run_log.status
     *
     * @return the value of job_run_log.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_run_log.remark
     *
     * @return the value of job_run_log.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_run_log.invoke_url
     *
     * @return the value of job_run_log.invoke_url
     *
     * @mbggenerated
     */
    public String getInvokeUrl() {
        return invokeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_run_log.created_at
     *
     * @return the value of job_run_log.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_run_log.created_by
     *
     * @return the value of job_run_log.created_by
     *
     * @mbggenerated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_run_log.updated_at
     *
     * @return the value of job_run_log.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_run_log.updated_by
     *
     * @return the value of job_run_log.updated_by
     *
     * @mbggenerated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_run_log.is_delete
     *
     * @return the value of job_run_log.is_delete
     *
     * @mbggenerated
     */
    public Integer getIsDelete() {
        return isDelete;
    }
}